User.create!([
  {first_name: "Diana", last_name: "Camacho", email: "diana@launchpadlab.com", encrypted_password: "$2a$11$wlbnplWHqI1lnaQyyaM67.Nc6mfSfRNjKbUYmkSbTT48i/PV0Fzja", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil},
  {first_name: nil, last_name: nil, email: "diana@test.com", encrypted_password: "$2a$11$qYAY6OetVXu/Wwr7eSvRxeCYX1bzuB/3kfiAugbKAnSlCyDA3TTr.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil}
])
Author.create!([
  {first_name: "J.K.", last_name: "Rowling", bio: "Joanne Rowling, who goes by the pen name J.K. Rowling, is a British author and screenwriter best known for her seven-book Harry Potter children's book series. The series has sold more than 450 million copies and was adapted into a blockbuster film franchise. \r\n\r\nRowling was living in Edinburgh, Scotland, and struggling to get by as a single mom before her first book, Harry Potter and the Sorcerer's Stone, was published in 1997. The children's fantasy novel became an international hit and Rowling became an international literary sensation in 1999 when the first three installments of Harry Potter took over the top three slots of The New York Times best-seller list after achieving similar success in her native United Kingdom. "},
  {first_name: "Harper", last_name: "Lee", bio: "Born April 28, 1926, Died February 19, 2016. Lee was an American novelist widely known for To Kill a Mockingbird, published in 1960. Immediately successful, it won the 1961 Pulitzer Prize and has become a classic of modern American literature. Though Lee had only published this single book, in 2007 she was awarded the Presidential Medal of Freedom for her contribution to literature."},
  {first_name: "Alice", last_name: "Walker", bio: "Alice Walker (born February 9, 1944) is an American novelist, short story writer, poet, and social activist. In 1982, she wrote the novel The Color Purple, for which she won the National Book Award for hardcover fiction, and the Pulitzer Prize for Fiction.[2][3] She also wrote the novels Meridian (1976) and The Third Life of Grange Copeland (1970)."},
  {first_name: "Suzanne", last_name: "Collins", bio: "Suzanne Collins (born August 10, 1962) is an American television writer and author. She is known as the author of The New York Times best-selling series The Underland Chronicles and The Hunger Games trilogy."},
  {first_name: "F. Scott", last_name: "Fitzgerald", bio: "Francis Scott Key Fitzgerald (September 24, 1896 – December 21, 1940) was an American fiction writer, whose works helped to illustrate the flamboyance and excess of the Jazz Age. While he achieved popular success, fame, and fortune in his lifetime,[1] he did not receive much critical acclaim until after his death. Perhaps the most notable member of the \"Lost Generation\" of the 1920s, Fitzgerald is now widely regarded as one of the greatest American writers of the 20th century. He finished four novels: This Side of Paradise, The Beautiful and Damned, The Great Gatsby, and Tender Is the Night. A fifth, unfinished novel, The Last Tycoon, was published posthumously. Four collections of his short stories were published, as well as 164 short stories in magazines during his lifetime."},
  {first_name: "Stephen", last_name: "King", bio: "Stephen Edwin King (born September 21, 1947) is an American author of horror, supernatural fiction, suspense, and fantasy novels. His books have sold more than 350 million copies,[2] many of which have been adapted into feature films, miniseries, television series, and comic books. King has published 61 novels (including seven under the pen name Richard Bachman) and six non-fiction books.[3] He has written approximately 200 short stories,[4][5] most of which have been published in book collections."},
  {first_name: "George R.R.", last_name: "Martin", bio: "George Raymond Richard Martin[1] (born George Raymond Martin, September 20, 1948),[2] also known as GRRM,[3] is an American novelist and short story writer in the fantasy, horror, and science fiction genres, screenwriter, and television producer. He is best known for his series of epic fantasy novels, A Song of Ice and Fire, which was adapted into the HBO series Game of Thrones (2011–2019)."}
])
Book.create!([
  {title: "Harry Potter and the Chamber of Secrets", summary: "Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series. The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the \"Chamber of Secrets\" has been opened and that the \"heir of Slytherin\" would kill all pupils who do not come from all-magical families. These threats are found after attacks which leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks.", genre: "Fantasy", publish_date: "2014-10-20", num_pages: 251, image_url: "https://upload.wikimedia.org/wikipedia/en/5/5c/Harry_Potter_and_the_Chamber_of_Secrets.jpg", author_id: 1},
  {title: "Harry Potter and the Sorcerer's Stone", summary: nil, genre: "Fantasy", publish_date: "2019-10-20", num_pages: 309, image_url: "https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg", author_id: 1}
])
Review.create!([
  {description: "testing harry", rating: 2, book_id: 1, user_id: 1}
])
